# Generated by Django 4.2.5 on 2023-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="durée",
            new_name="duree",
        ),
        migrations.RemoveField(
            model_name="action",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="action",
            name="ingredient",
            field=models.ManyToManyField(to="high_level.quantiteingredient"),
        ),
    ]
