# Generated by Django 4.2.5 on 2023-11-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0003_vente"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="high_level.action",
            ),
        ),
    ]
